### ISSUE TITLE
test environment

### ISSUE THREAD

**Issue by dhuang612** [Arcaster42/rhymus#24]
Hi,

I've been reviewing the way that you setup the mocha tests using chai.
I've noticed that jsdom is required into the project but we aren't using it to test any of the html dom elements?
Is this something that I can setup?

Also from the jsdom-mocha npm page:
Deprecation notice: Consider jsdom-global instead, a simpler alternative that also works outside of Mocha. mocha-jsdom still works, but jsdom-global is better supported.

https://www.npmjs.com/package/mocha-jsdom

**Comment by Arcaster42** [comment]
Feel free to use any additional packages for testing. Testing is a great thing, and we need to cover our code base.

**Comment by dhuang612** [comment]
okay,

I am going to keep working on this testing stuff then, thanks

**Comment by dhuang612** [comment]
working on the mocha tests, I noticed that the webspec tests aren't running since when you run
```
npm test
```

only 5 tests are showing as passing when there are actually around 20 tests if you include in the function testing.

**Comment by dhuang612** [comment]
created PR #48

**Comment by dhuang612** [comment]
I'll add some additional tests to cover code logic

**Comment by Arcaster42** [comment]
Thanks for your ongoing work improving the test code coverage.

**Comment by dhuang612** [comment]
created PR#51

**Comment by dhuang612** [comment]
created PR#52
tied up some loose ends
