### ISSUE TITLE
New Styling/Animations Needed

### ISSUE THREAD

**Issue by Arcaster42** [Arcaster42/rhymus#33]
Let's get some prettier CSS and added animations/effects in.

**Comment by CarlosMed** [comment]
I can help with that if youd like. Do you have something in mind or any library you may want to utilize?

**Comment by Arcaster42** [comment]
Nothing particular in mind. You have free reign. For this branch, please use vanilla JavaScript and CSS. We will use libraries in the other branches coming up.

**Comment by CarlosMed** [comment]
Sounds good, feel free to assign this issue to me and ill start as soon as possible.

**Comment by Arcaster42** [comment]
All yours! Looking forward to the changes.

**Comment by eekbatani** [comment]
I'll go ahead and see if I can make any improvements as well.
