### ISSUE TITLE
Timer / Wrong Answer Notification

### ISSUE THREAD

**Issue by Arcaster42** [Arcaster42/rhymus#35]
The timer is no longer present, so when the timer expires, you get a "wrong answer" notification without actually pressing enter. This confuses the player and feels very non-intuitive. Let's clean this up.

**Comment by josephting** [comment]
Are you saying to remove the timer and have unlimited time to answer?
Also, only count incorrect guesses with actual incorrect guesses by the player?

**Comment by Arcaster42** [comment]
Honestly I think it'd be better to have a global timer instead of time per card. Once the global timer reaches 0, the game ends.
