### ISSUE TITLE
Coding Standardization

### ISSUE THREAD

**Issue by Arcaster42** [Arcaster42/rhymus#39]
Over time, there have been some slight deviations with the code. Some hints are words, others are sentences; some sentences start capitalized, others are lowercase; punctuation is present, punctuation is missing. It would be great to have one person run through the `puzzles.js` and standardize all the code to have proper punctuation and consistent casing as well as review the code itself for consistency.

**Comment by guy-baron1** [comment]
Ill take this ;)

**Comment by Arcaster42** [comment]
This issue is still open and pending!
