### ISSUE TITLE
Score display upon game over

### ISSUE THREAD

**Issue by Arcaster42** [Arcaster42/rhymus#42]
Right now, once the game ends, you don't see your score anywhere. It would be nice to have a pop-up of some sort that shows points or a breakdown of correct vs missed. Bonus stats could include average time to answer question, if you're feeling bold.

**Comment by dbeigi** [comment]
Hey @Alacastra42, I can take a crack at this.

**Comment by Arcaster42** [comment]
Wrong username! But that's ok! It's all yours.

**Comment by dbeigi** [comment]
Oops! @Arcaster42 I don't know what happen.
