### ISSUE TITLE
wire up the start button

### ISSUE THREAD

**Issue by dhuang612** [Arcaster42/rhymus#49]
Hi,

I took a look at the app today, and noticed that the start button doesn't work.
Furthermore the timer begins immediately upon loading in the browser.
I was thinking that having to click the start button to begin the game might be something good to add.
That way everyone can choose the time that the game begins so that they can get a fair score, and not have to time it correctly to get the full 30 seconds?

If you agree, I can work on this.

Thanks

**Comment by Arcaster42** [comment]
I think having a manual start is a great idea! Go for it!

**Comment by dhuang612** [comment]
created PR#50
