### ISSUE TITLE
Vue conversion from vanilla JS

### ISSUE THREAD

**Issue by Arcaster42** [Arcaster42/rhymus#56]
The application is feature-complete in vanilla JS, but now there's a new `master-vue` branch to be done! You can use the existing `master` branch to model the component development. Unit tests and Vuex are available as needed.

**Comment by yuriechan** [comment]
Hi, 

When you say, 

> 'use the existing master branch to model the component development'

, is the whole purpose to initialize vue-app from scratch? 

How is this better than fetching your remote branch `master-vue` and start creating components on my feature branch?

**Comment by Arcaster42** [comment]
The meaning of that phrase is, make the Vue version as close to the master branch as possible. The branch containing Vue is currently just an initialization. There is some configuration done already, so this saves others from having to run the `vue create` command as well as figure out the basic configuration for things like the `vue.config.js` devServer and such. If you were to initialize your own Vue project and open a branch, Git would assume the files you initialized are intended to replace all existing files here.

**Comment by yuriechan** [comment]
Okay, then if I were to do this issue, I will base my feature branch from `master-vue` to create the components since you've initialized Vue and structured the folders already. I understand that I should be referring to the `master` branch for logic and UI. (At first, I misunderstood that we had to base our branch to `master`, instead of `master-vue`)

**Comment by yuriechan** [comment]
Also, should I open a PR per component? or should I open a PR once everything is converted into Vue?

**Comment by Arcaster42** [comment]
PRs should be done by feature. If a feature is large, implement a minimally viable iteration of it with a basic implementation of it.

**Comment by yuriechan** [comment]
I'm thinking of continuing to make commits to this issue to introduce `Vuex` to this application. 
Or, should I create a new issue specifically for adding `Vuex`?

**Comment by Arcaster42** [comment]
I'm going to make another branch specifically for a Vuex integration.

**Comment by Arcaster42** [comment]
You can now work from `master-vue-vuex` for the Vuex implementation. I'm going to close this issue now.
